#!/bin/bash

### global

#### binary
${_CMD_INS} vbindiff bsdiff

#### network
${_CMD_INS} whois

#### pwd & evtx & process
${_CMD_INS} john libscca-utils pev radare2

# r2env via pip3
python3 -m pip install -U r2env

#### hive
${_CMD_INS} libhivex-bin chntpw reglookup

#### gui
${_CMD_INS} bless geany ghex gpicview gtkhash wxhexeditor

### pip

python2 -m pip install -U balbuzard

python3 -m pip install -U malcarve regrippy

### base64sha

file=/usr/local/bin/b64sha
sudo curl -sS https://raw.githubusercontent.com/labcif/Base64SHA/master/b64sha -o ${file}
sudo chmod +x ${file}

### conf

#### bless
path=~/.config/bless/layouts/
[ -d "${path}" ] || mkdir -p ${path}
cp /usr/share/bless/*.layout ${path}/
